# Generated by Django 4.1.2 on 2022-11-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmDirectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='sinopsis',
            field=models.TextField(default='', help_text='Agrega una sinopsis de la película'),
        ),
    ]
