# Generated by Django 4.1.2 on 2022-11-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmDirectors', '0004_alter_director_films_alter_director_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='firstName',
            field=models.CharField(default=1, help_text='Nombre del director', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
