# Generated by Django 4.1.2 on 2022-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmDirectors', '0005_alter_director_firstname_alter_director_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='filmName',
            field=models.CharField(help_text='Pon el nombre de la película', max_length=100),
        ),
    ]
