# Generated by Django 4.1.2 on 2022-12-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmDirectors', '0006_alter_film_filmname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(help_text='Agrega un género', to='FilmDirectors.genre'),
        ),
    ]
